### ISSUE TITLE
Unexpected reserved word 'interface' when running on addon written in TypeScript using interfaces

### ISSUE THREAD

**Issue by jelhan** [ember-codemods/ember-component-template-colocation-migrator#21] opened 2020-09-01 10:06 UTC
I'm trying to use the codemod on Ember Power Select, which is an addon written in TypeScript. It throws these issue:

```
$ npx github:ember-codemods/ember-component-template-colocation-migrator
npx: Installierte 323 in 14.903s
SyntaxError: Unexpected reserved word 'interface' (7:0)
    at Parser._raise (/home/main/.npm/_npx/120043/lib/node_modules/ember-component-template-colocation-migrator/node_modules/@babel/parser/lib/index.js:766:17)
    at Parser.raiseWithData (/home/main/.npm/_npx/120043/lib/node_modules/ember-component-template-colocation-migrator/node_modules/@babel/parser/lib/index.js:759:17)
    at Parser.raise (/home/main/.npm/_npx/120043/lib/node_modules/ember-component-template-colocation-migrator/node_modules/@babel/parser/lib/index.js:753:17)
    at Parser.checkReservedWord (/home/main/.npm/_npx/120043/lib/node_modules/ember-component-template-colocation-migrator/node_modules/@babel/parser/lib/index.js:11132:14)
    at Parser.parseIdentifierName (/home/main/.npm/_npx/120043/lib/node_modules/ember-component-template-colocation-migrator/node_modules/@babel/parser/lib/index.js:11092:12)
    at Parser.parseIdentifier (/home/main/.npm/_npx/120043/lib/node_modules/ember-component-template-colocation-migrator/node_modules/@babel/parser/lib/index.js:11059:23)
    at Parser.parseExprAtom (/home/main/.npm/_npx/120043/lib/node_modules/ember-component-template-colocation-migrator/node_modules/@babel/parser/lib/index.js:10115:27)
    at Parser.parseExprSubscripts (/home/main/.npm/_npx/120043/lib/node_modules/ember-component-template-colocation-migrator/node_modules/@babel/parser/lib/index.js:9844:23)
    at Parser.parseUpdate (/home/main/.npm/_npx/120043/lib/node_modules/ember-component-template-colocation-migrator/node_modules/@babel/parser/lib/index.js:9824:21)
    at Parser.parseMaybeUnary (/home/main/.npm/_npx/120043/lib/node_modules/ember-component-template-colocation-migrator/node_modules/@babel/parser/lib/index.js:9813:17)
```

TypeScript support should have been added in #11. There is also test coverage for addons written in TypeScript: https://github.com/ember-codemods/ember-component-template-colocation-migrator/blob/d03ba9a7779d241b71b310807cc883ccd720cd09/test/lib/migrator/classic-to-nested-test.js#L130-L164 But the fixtures does not declare any interfaces.

**Comment by rwjblue** [comment] 2020-10-16 16:52
Hmm, would you mind adding one in the test cases so we can see if that also fails?

**Comment by donaldwasserman** [comment] 2021-02-22 16:44
cc @rwjblue @jelhan The issue is just using the wrong plugin name for typescript. Fixed in other PR.

**Closed as completed** 2021-04-14 23:40 UTC
